image: node:buster

pipelines:
  branches:
    # Run on merges to 'master' branch
    master:
      - step:
          name: Version Bump
          deployment: production
          script:
            # Get current version from package.json
            - VERSION=$(yarn version:current | sed -n '3 p')
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}
            - git tag "v${VERSION}" ${BITBUCKET_COMMIT}
            - git push origin --tags
