image: node:14.16-buster

pipelines:
  pull-requests:
    '**': # Run for any branch
      - step:
          name: Install dependencies
          caches: 
            - nodecustom
            - yarn
          script:
            - yarn --ignore-scripts --unsafe-perm
      - step:
          name: Run tests
          caches: 
            - nodecustom
            - yarn
          script:
            - yarn test --watchAll=false --passWithNoTests
      - step:
          name: Linting
          caches: 
            - nodecustom
            - yarn
          script:
            - yarn run eslint src/**/*.{ts,tsx}
      - step:
          name: Build
          caches: 
            - nodecustom
            - yarn
          script:
            - yarn build

  branches:
    # Run on merges to 'master' branch
    master:
      - step:
          name: Tag version bump
          deployment: production
          script:
            # https://support.atlassian.com/bitbucket-cloud/docs/push-back-to-your-repository/
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}
            - echo $PRIVATE_KEY > ~/.ssh/id_rsa.tmp
            - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            # Get current version from package.json and create new tag with it
            - VERSION=$(yarn version:current | sed -n '3 p')
            - git tag "v${VERSION}" ${BITBUCKET_COMMIT} && git push origin --tags || echo "Tag already exists, not creating new release"
      - step:
          name: Deploy to NPM
          caches:
            - nodecustom
            - yarn
          condition:
              changesets:
                  includePaths:
                    - "package.json"
          script:
            - unset NPM_CONFIG_USER
            - yarn --ignore-scripts --unsafe-perm
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
                EXTRA_ARGS: --access=public

definitions:
  caches:
    # https://community.atlassian.com/t5/Bitbucket-questions/Is-Yarn-supported-for-bitbucket-pipelines-caching/qaq-p/650816#M49760
    nodecustom: ./node_modules
    yarn: /usr/local/share/.cache/yarn
