name: Linting/Build/Tests

on:
  pull_request:
    branches: [master]
    # Trigger only with changes to any code
    paths: ["src/**"]

  push:
    branches: [master]
    # Trigger only with changes to any code
    paths: ["src/**"]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --prefer-offline --ignore-scripts

      - name: Run Eslint
        run: yarn run eslint "src/**/*.{ts,tsx}"

      - name: Run Tests
        run: yarn test

      - name: Run TypeScript Type-checking
        run: yarn run tsc --noEmit

      - name: Build
        run: yarn build
