name: Deploy Storybook
on: 
  push:
    branches: [master]
    paths: ["src/stories/**", "src/components/**", ".storybook/**", ".github/workflows/storybook_deploy.yml", "package.json"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --prefer-offline --ignore-scripts
      
      - name: Build storybook
        run: yarn build-storybook

      - name: Deploy storybook
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: docs
