name: Storybook Build

on:
  push:
    branches: [master]
    paths: ["src/stories/**", "src/components/**", ".storybook/**", ".github/workflows/storybook_deploy.yml"]

jobs:
  storybook:
    runs-on: ubuntu-latest
    env:
      # 7 GiB by default on GitHub, setting to 6 GiB
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      # https://github.com/storybookjs/builder-vite/issues/282#issuecomment-1072455178
      NODE_OPTIONS: --max-old-space-size=6144

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --prefer-offline --ignore-scripts

      - name: Storybook Build
        run: yarn build-storybook
